#!/bin/bash

# Make simple incremental backups with rsync.

set -eE

if [[ $EUID -ne 0 ]]; then
  echo "This script will not work unless it is run as root."
  exit 1
fi

LOG_FILE="/var/log/backup.log"
EXCLUDE_FILE="/usr/local/etc/backup/rsync-exclude.txt"
BACKUP_DIR="/media/$SUDO_USER/Backup/backups/sasquatch"
SRC_PATH="/"

TIMESTAMP="$(date '+%Y-%m-%d_%H-%M-%S')"
LATEST_LINK="$BACKUP_DIR/latest"
BACKUP_PATH="$BACKUP_DIR/$TIMESTAMP"
BACKUP_PATH_IN_PROGRESS="$BACKUP_PATH-in-progress"
BACKUP_PATH_FAILED="$BACKUP_PATH-failed"

echo "Running backup at $TIMESTAMP..." | tee -a "$LOG_FILE"

rsync --archive --no-devices --no-specials --acls --xattrs \
  --protect-args --verbose --progress \
  --exclude-from="$EXCLUDE_FILE" --link-dest="$LATEST_LINK" \
  --log-file="$LOG_FILE" \
  "$SRC_PATH" "$BACKUP_PATH_IN_PROGRESS" \
|| {
  echo "Failed to make backup that was started at $TIMESTAMP." \
    | tee -a "$LOG_FILE"
  mv -n "$BACKUP_PATH_IN_PROGRESS" "$BACKUP_PATH_FAILED"
  # Make sure this ends with an error exit code.
  false
} && {
  mv -n "$BACKUP_PATH_IN_PROGRESS" "$BACKUP_PATH" \
  && ln -rsfn "$BACKUP_PATH" "$LATEST_LINK" \
  && echo "Finished backup that was started at $TIMESTAMP." | tee -a "$LOG_FILE"
}
